# Generated by Django 5.0.14 on 2025-06-27 05:58

import apis.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0030_accountwiseinvestormasterdetailsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscationModeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transcationModeName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aumentrymodel',
            name='aumInvoiceNumber',
        ),
        migrations.AddField(
            model_name='dailyentrymodel',
            name='dailyEntryFile',
            field=models.FileField(blank=True, null=True, storage=apis.models.UniqueFileStorage(), upload_to='dailyEntryFile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='dailyentrymodel',
            name='dailyEntryTranscationMode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyEntryTranscationMode', to='apis.transcationmodemodel'),
        ),
    ]
