# Generated by Django 5.0.14 on 2025-07-19 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0031_transcationmodemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstentrymodel',
            name='gstArnNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gstArnNumber', to='apis.arnentrymodel'),
        ),
        migrations.AddField(
            model_name='gstentrymodel',
            name='gstRegistered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aumentrymodel',
            name='aumAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='aumyoygrowthentrymodel',
            name='aumYoyGrowthAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientinsurancemodel',
            name='clientInsurancePolicyMaturityAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientmedicalinsurancemodel',
            name='clientMedicalInsurancePolicyMaturityAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='clientAnnualIncome',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientterminsurancemodel',
            name='clientTermInsurancePolicyMaturityAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='commissionentrymodel',
            name='commissionAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='dailyentrymodel',
            name='dailyEntryAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='gstentrymodel',
            name='gstCGst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='gstentrymodel',
            name='gstIGst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='gstentrymodel',
            name='gstSGst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='gstentrymodel',
            name='gstTaxableValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='gstentrymodel',
            name='gstTotalValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='industryaumentrymodel',
            name='industryAumAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='statementmodel',
            name='statementCostOfInvestment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='statementmodel',
            name='statementCurrentValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='statementmodel',
            name='statementSipAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='statementmodel',
            name='statementSwpAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
